<?php

/**
 * @file
 * Configuration structure inspector module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function config_inspector_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'config_inspector.overview':
      return '<p>' . t('List of configuration keys to review with their configuration schema. Keys that have no schema are displayed but only raw data review is possible. Check out the <a href=":schema_link">configuration schema documentation</a> for more details.', [':schema_link' => 'https://drupal.org/node/1905070']) . '</p>';
  }
}

/**
 * Implements hook_validation_constraint_alter().
 */
function config_inspector_validation_constraint_alter(array &$definitions) {
  // @todo Remove when we require Drupal 10.3.x.
  if (isset($definitions['ValidKeys']) && version_compare(\Drupal::VERSION, '10.3', 'lt')) {
    // phpcs:ignore Drupal.Classes.FullyQualifiedNamespace.UseStatementMissing
    $definitions['ValidKeys']['class'] = \Drupal\config_inspector\ForwardPort\Plugin\Validation\Constraint\ValidKeysConstraint::class;
  }
}
