<?php

declare(strict_types=1);

namespace Drupal\diff\Routing;

use Drupal\Core\Entity\Controller\VersionHistoryController;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Routing\RouteSubscriberBase;
use Drupal\Core\Routing\RoutingEvents;
use Symfony\Component\Routing\RouteCollection;

/**
 * Listens to the dynamic route events.
 */
class RouteSubscriber extends RouteSubscriberBase {

  public function __construct(
    protected EntityTypeManagerInterface $entityTypeManager,
  ) {
  }

  /**
   * {@inheritdoc}
   */
  public static function getSubscribedEvents(): array {
    $events = [];
    // Let other modules' route subscribers happen first.
    $events[RoutingEvents::ALTER] = ['onAlterRoutes', -50];
    return $events;
  }

  /**
   * {@inheritdoc}
   */
  public function alterRoutes(RouteCollection $collection) {
    // Replace the content from node.revision_overview route with content
    // generated by revisionOverview method from NodeRevisionController class.
    $route = $collection->get('entity.node.version_history');
    if ($route !== NULL) {
      $route->addDefaults(
        [
          '_controller' => '\Drupal\diff\Controller\NodeRevisionController::revisionOverview',
        ],
      );
    }

    $entity_types = $this->entityTypeManager->getDefinitions();
    foreach ($entity_types as $entity_type) {
      // Node already handled.
      if ($entity_type->id() === 'node') {
        continue;
      }
      if (!$entity_type->hasLinkTemplate('revisions-diff') || !$entity_type->hasHandlerClass('route_provider', 'html_diff')) {
        // No route provided to power the diff view.
        continue;
      }

      $route = $collection->get("entity.{$entity_type->id()}.version_history");
      $controller = $route?->getDefault('_controller');
      if ($route !== NULL && $controller === VersionHistoryController::class) {
        $route->addDefaults(
          [
            '_controller' => '\Drupal\diff\Controller\EntityRevisionController::revisionOverview',
            '_entity_revisions_overview' => $entity_type->id(),
          ],
        );
      }
    }
  }

}
