<?php

/**
 * @file
 * File containing hooks for search api block module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Need to don't see the parameters 'form_build_id' and 'form_id' in the url
 * in order to make the search work.
 */
function search_api_block_form_search_api_form_alter(&$form, FormStateInterface $form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function search_api_block_theme_suggestions_input_alter(array &$suggestions, array $variables) {
  // @todo Use #context when https://www.drupal.org/project/drupal/issues/2511548 lands.
  if (!empty($variables['element']['#search_api_block'])) {
    $suggestions[] = $variables['theme_hook_original'] . '__search_api_block';
  }
}
