<?php

/**
 * @file
 * Main functions for "Paragraphs Editor Enhancements" module.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\paragraphs\Entity\ParagraphsType;
use Drupal\paragraphs\ParagraphsTypeInterface;
use Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget;
use Drupal\paragraphs_ee\Entity\ParagraphsCategory;
use Drupal\paragraphs_ee\ParagraphsEE;

/**
 * Implements hook_theme().
 */
function paragraphs_ee_theme(): array {
  return [
    'paragraphs_add_dialog__categorized' => [
      'render element' => 'element',
      'template' => 'paragraphs-add-dialog--categorized',
    ],
    'input__submit__paragraph_action__image' => [
      'base hook' => 'input',
      'render element' => 'element',
      'template' => 'input--submit--paragraph_action--image',
      'path' => \Drupal::service('extension.list.module')->getPath('paragraphs_ee') . '/templates',
    ],
  ];
}

/**
 * Implements hook_field_widget_single_element_form_alter().
 */
function paragraphs_ee_field_widget_single_element_form_alter(array &$element, FormStateInterface &$form_state, array $context): void {
  if (!($context['widget'] instanceof ParagraphsWidget)) {
    return;
  }

  // Add custom library.
  $element['#attached']['library'][] = 'paragraphs_ee/paragraphs_ee.paragraphs';
  if (empty($element['#attached']['drupalSettings']['paragraphs_features'])) {
    // If the widget is not configured to use one of the features provided by
    // the module, this would not exist and cause an error.
    $element['#attached']['drupalSettings']['paragraphs_features'] = [];
  }
}

/**
 * Implements hook_field_widget_complete_form_alter().
 */
function paragraphs_ee_field_widget_complete_form_alter(array &$field_widget_complete_form, FormStateInterface $form_state, array $context): void {
  /** @var \Drupal\paragraphs\Plugin\Field\FieldWidget\ParagraphsWidget $widget */
  $widget = $context['widget'];
  if (!($widget instanceof ParagraphsWidget && !empty($field_widget_complete_form['widget']))) {
    return;
  }

  $elements = &$field_widget_complete_form['widget'];

  // Check if modifications to widget are allowed.
  $hook_arguments = [$elements, $form_state, $context];
  $access_results = \Drupal::moduleHandler()->invokeAll('paragraphs_ee_widget_access', $hook_arguments);
  /** @var \Drupal\Core\Access\AccessResultInterface $result */
  $result = AccessResult::neutral();
  if (!empty($access_results)) {
    $result = array_shift($access_results);
    foreach ($access_results as $access_result) {
      $result = $result->orIf($access_result);
    }
  }
  if ($result->isForbidden()) {
    return;
  }

  // Load all available paragraph types.
  $types_available = [];
  if (isset($elements['add_more'])) {
    $types_available = ParagraphsType::loadMultiple(array_column($elements['add_more'], '#bundle_machine_name'));
  }

  foreach (Element::getVisibleChildren($elements) as $child_key) {
    if (isset($elements[$child_key]['top']['type']['label']['#markup']) && isset($types_available[$elements[$child_key]['#paragraph_type']])) {
      // Use translated bundle label.
      $elements[$child_key]['top']['type']['label']['#markup'] = '<span class="paragraph-type-label">' . $types_available[$elements[$child_key]['#paragraph_type']]->label() . '</span>';
    }
  }

  // Add support for the modal dialog.
  if (($widget->getSetting('add_mode') === 'modal') && isset($elements['add_more'])) {
    if ($form_state->get('paragraphs_ee-add_mode') === 'off_canvas') {
      unset($elements['add_more']['add_modal_form_area']);
    }

    /** @var \Drupal\entity_reference_revisions\EntityReferenceRevisionsFieldItemList $items */
    $items = $context['items'];

    // Add custom library.
    $elements['#attached']['library'][] = 'paragraphs_ee/paragraphs_ee.paragraphs';

    $field_definition_settings = (array) $items->getFieldDefinition()->getSetting('handler_settings');

    $buttons_ref = [];
    /** @var \Drupal\paragraphs\Entity\ParagraphsType $type */
    foreach ($types_available as $id => $type) {
      $button_id = "add_more_button_{$id}";
      $button = $elements['add_more'][$button_id];

      // Use custom button layout (and rewrite <input> to <button>).
      $button['#theme_wrappers'] = ['input__submit__paragraph_action__image'];
      $button['#attributes']['class'][] = 'paragraphs-button--add-more';

      // Set translated label as value.
      $button['#value'] = $type->label();
      // Set button description.
      $button['#description'] = $type->getDescription();

      $button['#icon_attributes'] = new Attribute();
      $button['#icon_attributes']['aria-hidden'] = 'true';
      $button['#icon_attributes']['class'] = ['paragraphs-button--icon'];
      if ($icon_url = $type->getIconUrl()) {
        // Extract icon from button.
        $button['#attributes']['class'][] = 'icon';
        unset($button['#attributes']['style']);
        $button['#icon'] = $icon_url;
      }
      else {
        $button['#icon_attributes']['class'][] = 'image-default';
      }
      $button['#weight'] = 0;
      if (isset($field_definition_settings['target_bundles_drag_drop'][$id]['weight'])) {
        $button['#weight'] = $field_definition_settings['target_bundles_drag_drop'][$id]['weight'];
      }
      $elements['add_more'][$button_id] = $button;

      $settings = array_filter((array) $type->getThirdPartySetting('paragraphs_ee', 'paragraphs_categories', []));
      if (empty($settings)) {
        // Store category for later use.
        $elements['add_more'][$button_id]['#paragraphs_category'] = '_none';
        // Paragraph type is uncategorized so we do not need to process it here.
        continue;
      }
      // We need to call this first because the value is changed on second run
      // only.
      Html::getUniqueId($button_id);
      foreach ($settings as $paragraphs_category) {
        $buttons_ref[$button_id] = empty($buttons_ref[$button_id]) ? 1 : ($buttons_ref[$button_id] + 1);
        if (empty($elements['add_more'][$button_id]['#paragraphs_category'])) {
          // Store category for later use.
          $elements['add_more'][$button_id]['#paragraphs_category'] = $paragraphs_category;
          continue;
        }

        // Clone button and change some attributes so AJAX is working.
        $button['#id'] = Html::getUniqueId($button['#id']);
        $button_new_id = strtr(Html::getUniqueId($button_id), ['-' => '_']);
        $button['#name'] .= '__' . $buttons_ref[$button_id];
        $button['#attributes']['data-paragraphs-ee-button-clone'] = '';
        // Add clone of button to add_more-element.
        $elements['add_more'][$button_new_id] = $button;
        // Store category for later use.
        $elements['add_more'][$button_new_id]['#paragraphs_category'] = $paragraphs_category;
      }
    }

    uasort($elements['add_more'], 'Drupal\Component\Utility\SortArray::sortByWeightProperty');

    $widget_third_party_settings = (array) $widget->getThirdPartySetting('paragraphs_ee', 'paragraphs_ee', []);

    $easy_access_buttons = [];
    $easy_access_count = $widget->getThirdPartySetting('paragraphs_features', 'add_in_between_link_count', 3);
    // Mark the first unique buttons for easy access.
    foreach (Element::children($elements['add_more']) as $child_key) {
      if (empty($elements['add_more'][$child_key]['#bundle_machine_name'])) {
        continue;
      }
      $bundle_machine_name = $elements['add_more'][$child_key]['#bundle_machine_name'];
      if (count($easy_access_buttons) >= $easy_access_count) {
        // No need to process more elements as we reached the limit already.
        break;
      }
      if (isset($easy_access_buttons[$bundle_machine_name])) {
        // Button is already in list and is not added again.
        continue;
      }
      $easy_access_buttons[$bundle_machine_name] = $elements['add_more'][$child_key]['#weight'];
      $elements['add_more'][$child_key]['#easy_access'] = TRUE;
      $elements['add_more'][$child_key]['#attributes']['data-easy-access-weight'] = $elements['add_more'][$child_key]['#weight'];
      $elements['add_more'][$child_key]['#attributes']['data-paragraph-bundle'] = $bundle_machine_name;
    }

    $elements['#attached']['drupalSettings']['paragraphs_ee']['dialog_style'] = 'tiles';
    // Use different theme for modal dialog.
    $elements['add_more']['#theme'] = 'paragraphs_add_dialog__categorized';
    $elements['add_more']['#wrapper_attributes'] = new Attribute();
    $elements['add_more']['#wrapper_attributes']['class'] = [
      'paragraphs-ee-dialog-wrapper',
      'js-hide',
    ];

    $elements['add_more']['#wrapper_attributes']['data-sidebar-disabled'] = FALSE;
    if (!empty($widget_third_party_settings['sidebar_disabled'])) {
      $elements['add_more']['#wrapper_attributes']['class'][] = 'sidebar-hidden';
      $elements['add_more']['#wrapper_attributes']['data-sidebar-disabled'] = TRUE;
    }

    $elements['add_more']['#dialog_attributes'] = new Attribute();
    $elements['add_more']['#dialog_attributes']['class'] = [
      'clearfix',
      'paragraphs-add-dialog',
      'paragraphs-add-dialog--categorized',
    ];

    if (!empty($widget_third_party_settings['dialog_style']) && ('tiles' !== $widget_third_party_settings['dialog_style'])) {
      $elements['#attached']['drupalSettings']['paragraphs_ee']['dialog_style'] = $widget_third_party_settings['dialog_style'];
      $elements['add_more']['#dialog_attributes']['class'][] = 'paragraphs-style-' . $widget_third_party_settings['dialog_style'];
    }

    $elements['add_more']['#dialog_attributes']['role'] = 'dialog';
    $elements['add_more']['#dialog_attributes']['aria-modal'] = 'true';
    $elements['add_more']['#dialog_attributes']['aria-label'] = t('Add @widget_title', ['@widget_title' => $widget->getSetting('title')], ['context' => 'Paragraphs Editor Enhancements']);
    $elements['add_more']['#dialog_attributes']['data-widget-title'] = $widget->getSetting('title');
    $elements['add_more']['#dialog_attributes']['data-widget-title-plural'] = $widget->getSetting('title_plural');
    $elements['add_more']['#dialog_attributes']['data-paragraphs-ee-dialog-wrapper'] = '';
    $elements['add_more']['#attached']['library'][] = 'paragraphs_ee/paragraphs_ee.categories';

    if (!empty($widget_third_party_settings['dialog_off_canvas'])) {
      /** @var \Drupal\Core\Entity\Display\EntityFormDisplayInterface|null $form_display */
      $form_display = $form_state->get('form_display');
      $elements['add_more']['#dialog_attributes']['data-dialog-off-canvas'] = 'true';
      $elements['add_more']['#dialog_attributes']['data-dialog-field-name'] = $items->getFieldDefinition()->getName();

      // Check if form_display is available before using it.
      if (!is_null($form_display)) {
        $browser_params = [
          'entity_type' => $form_display->getTargetEntityTypeId(),
          'bundle' => $form_display->getTargetBundle(),
          'form_mode' => $form_display->getMode(),
          'field_name' => $items->getFieldDefinition()->getName(),
        ];
        $elements['add_more']['#dialog_attributes']['data-dialog-browser-url'] = Url::fromRoute('paragraphs_ee.paragraphs_browser', $browser_params)->toString();

        $elements['#dialog_attributes']['data-paragraphs-ee'] = '';
      }
    }
  }

  // Add gin accent library.
  ParagraphsEE::addGinAccents($elements);

  // Register custom widget features.
  ParagraphsEE::registerWidgetFeatures($elements, $widget);
}

/**
 * Prepare variables used in paragraphs-add-dialog--categorized.html.twig.
 *
 * @param array $variables
 *   An associative array containing variables used in the template.
 */
function template_preprocess_paragraphs_add_dialog__categorized(&$variables): void {
  // Define variables for the template.
  $variables += ['buttons' => []];
  $variables['add_mode'] = $variables['element']['#add_mode'] ?? 'modal';
  $variables['add'] = [];
  if (isset($variables['element']['add_modal_form_area'])) {
    $variables['add']['add_modal_form_area'] = $variables['element']['add_modal_form_area'];
  }
  if (isset($variables['element']['add_more_delta'])) {
    $variables['add']['add_more_delta'] = $variables['element']['add_more_delta'];
  }
  /** @var \Drupal\paragraphs_ee\ParagraphsCategoryInterface[] $paragraphs_categories */
  $paragraphs_categories = \Drupal::entityTypeManager()->getStorage('paragraphs_category')
    ->loadMultiple();
  // Sort the entities using the entity class's sort() method.
  // See \Drupal\Core\Config\Entity\ConfigEntityBase::sort().
  uasort($paragraphs_categories, [ParagraphsCategory::class, 'sort']);
  $category_translation_arguments = [
    '@title' => $variables['element']['#dialog_attributes']['data-widget-title'],
    '@title_plural' => $variables['element']['#dialog_attributes']['data-widget-title-plural'],
  ];

  $variables['categories']['_all'] = [
    'title' => t('All'),
    'link_title' => t('Show all @title_plural', $category_translation_arguments),
    'description' => '',
    'id' => 'all',
  ];

  $category_names = array_keys($paragraphs_categories);
  $grouped = array_combine($category_names, array_fill(0, count($category_names), []));
  /** @var Drupal\paragraphs_ee\ParagraphsCategoryInterface $category */
  foreach ($paragraphs_categories as $key => $category) {
    $conditional_id = isset($variables['element']['#id']) ? $variables['element']['#id'] . '-category-' . $key : 'category-' . $key;
    $category_translation_arguments['@category_title'] = $category->label();
    $variables['categories'][$key] = [
      'title' => $category->label(),
      'link_title' => t('Show @category_title only', $category_translation_arguments),
      'description' => $category->getDescription(),
      'id' => Html::getUniqueId($conditional_id),
    ];
  }
  $variables['categories']['_none'] = [
    'title' => t('Uncategorized'),
    'link_title' => t('Show uncategorized @title_plural', $category_translation_arguments),
    'description' => '',
    'id' => Html::getUniqueId('uncategorized'),
  ];
  // Add category for uncategorized items.
  $grouped['_none'] = [];
  foreach (Element::children($variables['element']) as $element_key) {
    if (empty($variables['element'][$element_key]['#paragraphs_category'])) {
      continue;
    }
    // Add button to category.
    $grouped[$variables['element'][$element_key]['#paragraphs_category']][] = $variables['element'][$element_key];
  }
  $variables['wrapper_attributes'] = $variables['element']['#wrapper_attributes'];
  $variables['dialog_attributes'] = $variables['element']['#dialog_attributes'];
  $variables['groups'] = array_filter($grouped);

  // Remove all empty categories.
  $empty_categories = array_diff(array_keys($grouped), array_keys(array_filter($grouped)));
  if (count($empty_categories) > 0) {
    $variables['categories'] = array_diff_key($variables['categories'], array_flip($empty_categories));
  }

  $placeholder_value = 'Paragraphs';
  if (isset($variables['element']['#dialog_attributes']['data-widget-title-plural'])) {
    $placeholder_value = (string) $variables['element']['#dialog_attributes']['data-widget-title-plural'];
  }
  $variables['filter_placeholder'] = t('Search', [], ['context' => 'Paragraphs Editor Enhancements']);
  $variables['filter_description'] = t('Search @placeholder_value by title and description', ['@placeholder_value' => $placeholder_value], ['context' => 'Paragraphs Editor Enhancements']);
  $variables['sidebar_disabled'] = $variables['element']['#wrapper_attributes']['data-sidebar-disabled'] ?? FALSE;
}

/**
 * Prepare variables used in input--submit--paragraph_action--image.html.twig.
 */
function paragraphs_ee_preprocess_input__submit__paragraph_action__image(array &$vars): void {
  $element = $vars['element'];

  // Add title and description as custom element.
  $vars['title'] = $element['#value'];
  $vars['description'] = $element['#description'];
  $vars['label_id'] = empty($vars['attributes']['aria-labeledby']) ? NULL : $vars['attributes']['aria-labeledby'];
  $vars['description_id'] = empty($vars['attributes']['aria-describedby']) ? NULL : $vars['attributes']['aria-describedby'];

  $icon_attributes = $element['#icon_attributes'];
  if (isset($element['#icon'])) {
    $icon_attributes['style'] = 'background-image: url("' . $element['#icon'] . '");';
  }
  $vars['icon_attributes'] = $icon_attributes;
}
